/** Seed tài khoản — tách khỏi mock để store mutable */

export const ADMIN_USERS_SEED = [
  {
    id: "u1",
    username: "anhcoding12345",
    email: "tngo28299@gmail.com",
    displayName: "Anhpika",
    role: "student",
    plan: "Free",
    status: "active",
    joinedAt: "2025-09-12",
  },
  {
    id: "u2",
    username: "minhanh_dev",
    email: "minhanh@fpt.edu.vn",
    displayName: "Trần Minh Anh",
    role: "student",
    plan: "Premium",
    status: "active",
    joinedAt: "2025-11-03",
  },
  {
    id: "u3",
    username: "mod_sehub",
    email: "moderator@sehubs.local",
    displayName: "Nguyễn Kiểm Duyệt",
    role: "moderator",
    plan: "—",
    status: "active",
    joinedAt: "2025-08-01",
  },
  {
    id: "u4",
    username: "spam_bot_01",
    email: "spam@fake.mail",
    displayName: "Spam Bot",
    role: "student",
    plan: "Free",
    status: "banned",
    joinedAt: "2026-05-20",
  },
  {
    id: "u5",
    username: "lee_dev_99",
    email: "lee.dev@fpt.edu.vn",
    displayName: "Lê Văn Đức",
    role: "student",
    plan: "Free",
    status: "active",
    joinedAt: "2026-01-08",
  },
  {
    id: "u6",
    username: "tran_van_a",
    email: "tranva@fpt.edu.vn",
    displayName: "Trần Văn A",
    role: "student",
    plan: "Premium",
    status: "active",
    joinedAt: "2025-12-14",
  },
  {
    id: "u7",
    username: "pham_thi_b",
    email: "phamtb@fpt.edu.vn",
    displayName: "Phạm Thị B",
    role: "student",
    plan: "Free",
    status: "active",
    joinedAt: "2026-02-22",
  },
  {
    id: "u8",
    username: "mod_phuong",
    email: "phuong.mod@sehubs.local",
    displayName: "Hoàng Phương Mod",
    role: "moderator",
    plan: "—",
    status: "active",
    joinedAt: "2025-07-19",
  },
  {
    id: "u9",
    username: "fpt_student_22",
    email: "fpt22@student.vn",
    displayName: "Nguyễn FPT 22",
    role: "student",
    plan: "Premium",
    status: "active",
    joinedAt: "2026-03-05",
  },
  {
    id: "u10",
    username: "scammer_xyz",
    email: "scam@fake.mail",
    displayName: "Scammer XYZ",
    role: "student",
    plan: "Free",
    status: "banned",
    joinedAt: "2026-04-18",
  },
  {
    id: "u11",
    username: "helpdesk_req_88",
    email: "help88@fpt.edu.vn",
    displayName: "Support Test 88",
    role: "student",
    plan: "Free",
    status: "active",
    joinedAt: "2026-05-01",
  },
  {
    id: "u12",
    username: "user_4421",
    email: "user4421@mail.com",
    displayName: "User 4421",
    role: "student",
    plan: "Free",
    status: "active",
    joinedAt: "2025-10-30",
  },
  {
    id: "u13",
    username: "admin_backup",
    email: "backup@sehubs.local",
    displayName: "Admin Backup",
    role: "admin",
    plan: "—",
    status: "active",
    joinedAt: "2025-06-01",
  },
  {
    id: "u14",
    username: "coding_ninja",
    email: "ninja@dev.vn",
    displayName: "Coding Ninja",
    role: "student",
    plan: "Premium",
    status: "active",
    joinedAt: "2025-11-28",
  },
  {
    id: "u15",
    username: "vu_minh_c",
    email: "vuminhc@fpt.edu.vn",
    displayName: "Vũ Minh C",
    role: "student",
    plan: "Free",
    status: "active",
    joinedAt: "2026-04-02",
  },
  {
    id: "u16",
    username: "banned_temp_01",
    email: "temp01@fake.mail",
    displayName: "Banned Temp",
    role: "student",
    plan: "Free",
    status: "banned",
    joinedAt: "2026-05-10",
  },
  {
    id: "u17",
    username: "hoa_nguyen_d",
    email: "hoand@fpt.edu.vn",
    displayName: "Hoa Nguyễn D",
    role: "student",
    plan: "Premium",
    status: "active",
    joinedAt: "2025-09-25",
  },
  {
    id: "u18",
    username: "mod_khanh",
    email: "khanh.mod@sehubs.local",
    displayName: "Trần Khánh Mod",
    role: "moderator",
    plan: "—",
    status: "active",
    joinedAt: "2025-10-12",
  },
  {
    id: "u19",
    username: "study_group_7",
    email: "sg7@fpt.edu.vn",
    displayName: "Study Group 7",
    role: "student",
    plan: "Free",
    status: "active",
    joinedAt: "2026-02-08",
  },
  {
    id: "u20",
    username: "premium_trial",
    email: "trial@fpt.edu.vn",
    displayName: "Premium Trial",
    role: "student",
    plan: "Premium",
    status: "active",
    joinedAt: "2026-05-25",
  },
  {
    id: "u21",
    username: "user_xyz",
    email: "userxyz@fpt.edu.vn",
    displayName: "User XYZ",
    role: "student",
    plan: "Free",
    status: "active",
    joinedAt: "2026-03-18",
  },
  {
    id: "u22",
    username: "toxic_user_99",
    email: "toxic99@fake.mail",
    displayName: "Toxic User 99",
    role: "student",
    plan: "Free",
    status: "active",
    joinedAt: "2026-04-11",
  },
  {
    id: "u23",
    username: "seller_01",
    email: "seller01@fake.mail",
    displayName: "Seller 01",
    role: "student",
    plan: "Free",
    status: "active",
    joinedAt: "2026-02-14",
  },
  {
    id: "u24",
    username: "news_fake",
    email: "newsfake@fake.mail",
    displayName: "News Fake",
    role: "student",
    plan: "Free",
    status: "active",
    joinedAt: "2026-01-20",
  },
  {
    id: "u25",
    username: "promo_acc",
    email: "promo@fake.mail",
    displayName: "Promo Account",
    role: "student",
    plan: "Free",
    status: "active",
    joinedAt: "2026-05-08",
  },
];
