import {
  faAlignLeft,
  faBold,
  faCode,
  faHighlighter,
  faImage,
  faItalic,
  faLink,
  faLinkSlash,
  faListOl,
  faListUl,
  faMinus,
  faPalette,
  faPaperclip,
  faQuoteLeft,
  faSquareRootVariable,
  faStrikethrough,
  faTable,
  faUnderline,
} from "@fortawesome/free-solid-svg-icons";

export const TOOLBAR_VARIANTS = {
  full: [
    "paragraph",
    "bold",
    "italic",
    "strikethrough",
    "color",
    "code",
    "link",
    "image",
    "table",
    "bulletList",
    "orderedList",
    "quote",
    "horizontalRule",
    "alignLeft",
  ],
  comment: [
    "bold",
    "italic",
    "strikethrough",
    "highlight",
    "code",
    "link",
    "unlink",
    "image",
    "attach",
    "bulletList",
    "orderedList",
    "quote",
    "alignLeft",
  ],
  basic: ["bold", "italic", "underline", "bulletList", "orderedList", "link", "code"],
  minimal: ["formula", "image"],
};

export const TOOL_DEFINITIONS = {
  paragraph: { label: "Đoạn văn", glyph: "¶" },
  bold: { label: "In đậm", icon: faBold },
  italic: { label: "In nghiêng", icon: faItalic },
  underline: { label: "Gạch chân", icon: faUnderline },
  strikethrough: { label: "Gạch ngang", icon: faStrikethrough },
  highlight: { label: "Đánh dấu", icon: faHighlighter },
  color: { label: "Màu chữ", icon: faPalette },
  code: { label: "Mã", icon: faCode },
  link: { label: "Liên kết", icon: faLink },
  unlink: { label: "Gỡ liên kết", icon: faLinkSlash },
  image: { label: "Hình ảnh", icon: faImage },
  attach: { label: "Đính kèm", icon: faPaperclip },
  table: { label: "Bảng", icon: faTable },
  bulletList: { label: "Danh sách", icon: faListUl },
  orderedList: { label: "Danh sách đánh số", icon: faListOl },
  quote: { label: "Trích dẫn", icon: faQuoteLeft },
  horizontalRule: { label: "Kẻ ngang", icon: faMinus },
  alignLeft: { label: "Căn trái", icon: faAlignLeft },
  formula: { label: "Chèn công thức", icon: faSquareRootVariable },
};
